Print success/failure in unit test script
Signed-off-by: Chris Piraino <cpiraino@pivotal.io>

diff --git a/scripts/run-unit-tests b/scripts/run-unit-tests
--- a/scripts/run-unit-tests
+++ b/scripts/run-unit-tests
@@ -2,6 +2,16 @@
 
 set -e -x
 
+function printStatus {
+  if [ $? -eq 0 ]; then
+    echo -e "\nSWEET SUITE SUCCESS"
+  else
+    echo -e "\nSUITE FAILURE"
+  fi
+}
+
+trap printStatus EXIT
+
 bin_dir=$(dirname $0)/../bin
 
 tmpdir=$(mktemp -d /tmp/cf-routing-downloads.XXXX)
