ci: syslog-test can use toolsmiths env
[#169068487](https://www.pivotaltracker.com/story/show/169068487)

Co-authored-by: Bruce Ricard <bricard@pivotal.io>

diff --git a/ci/tasks/syslog-test/task b/ci/tasks/syslog-test/task
--- a/ci/tasks/syslog-test/task
+++ b/ci/tasks/syslog-test/task
@@ -3,8 +3,15 @@ set -eu -o pipefail
 
 source networking-oss-tools/scripts/script_helpers.sh
 
-ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
-bosh_login "${ENVIRONMENT}"
+if [[ -d toolsmiths-metadata-dir ]]; then
+  bosh_login_toolsmiths toolsmiths-metadata-dir
+elif [[ -d networking-oss-deployments ]]; then
+  ENVIRONMENT="${ENVIRONMENT:?"ENVIRONMENT not set"}"
+  bosh_login "${ENVIRONMENT}"
+else
+  echo "Failed to provide either \"toolsmiths-metadata-dir\" or \"networking-oss-deployments\""
+  exit 1
+fi
 
 function cleanup() {
   pkill ssh || true
