fix: make job go red when it fails
* in the old way, the test could fail, but popd would be the last command run, so it
always would exit 0 and show green on concourse
* fix Jubilee

Co-authored-by: Clay Kauzlaric <ckauzlaric@pivotal.io>

diff --git a/ci/tasks/check-zero-downtime-test-results/task b/ci/tasks/check-zero-downtime-test-results/task
--- a/ci/tasks/check-zero-downtime-test-results/task
+++ b/ci/tasks/check-zero-downtime-test-results/task
@@ -13,4 +13,8 @@ git clone https://github.com/cf-routing/routehealthparser.git
 pushd routehealthparser
 	echo "Now checking if there were any 500's or 404's during deploy"
 	go run main.go --address=${APP_URL}/health
+	if [[ $? -ne 0 ]]; then
+		echo 'The tests failed'
+		exit 1
+	fi
 popd
